### ISSUE TITLE
Remove Vetur dependency

### ISSUE THREAD

**Issue by devmor-j** [xianghongai/vscode-vue3-snippets#1]
Hey, I use vue2 snippets without vetur (I use volar). If vetur is not required for this extension to work properly, could you please remove it from dependencies.

**Comment by xianghongai** [comment]
Thanks for your feedback, Vetur dependency has been removed, `v0.0.8` has been released, please try it.

**Comment by devmor-j** [comment]
Thanks for your response. I installed it works great.
